name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://jagriti2325:$HF_TOKEN@huggingface.co/spaces/JagritiArora/Kawach-Diagnostic-Final
          # This only pushes the code and skips the heavy history/LFS issues
          git push --force hf main
